server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security?serverTimezone=Asia/Seoul
    username: cos
    password: cos1234
    

  jpa:
    hibernate:
      ddl-auto: update #create update none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 193501129278-73tt949qv9n8ra4s89o1ulhbamrfj3n6.apps.googleusercontent.com
            client-secret: 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
            scope:
            - email
            - profile
            
          facebook:
            client-id: 202836986084896
            client-secret: 8e90eaaed3a714408051e2f094a516a7
            scope: public_profile,email
          
          naver:
            client-id: VBLebqWtgiblOeOdV8pQ
            client-secret: Brx0ttXpJX
            scope:
            - name
            - email
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver

        provider: 
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response #회원정보를 json으로 받는데 response라는 키값으로 리턴해줌
                